sudo: required

language: php

dist: xenial

services:
  - mysql

php:
  - 7.2

env:
  global:
    - MOODLE_BRANCH=master
    - IGNORE_PATHS=amd/build,amd/src/bootstrap.js
    - IGNORE_NAMES=*.txt,moodle.css,moodle-rtl.css,moodle_min.css,editor.css,editor_min.css,Gruntfile.js
    - DB=mysqli

matrix:
  - php: 7.2
    env: DB=mysqli   TASK=PHPUNIT

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci jshint
  #- moodle-plugin-ci phpunit